### ISSUE TITLE
Marshmallow permission 

### ISSUE THREAD

**Issue by hinaloe** [kb10uy/Tencocoa#19]
```
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.kb10uy.tencocoa, PID: 3749
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kb10uy.tencocoa/org.kb10uy.bhavaagra.MediaSelectorActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=3749, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=3749, uid=10057 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                       at android.os.Parcel.readException(Parcel.java:1599)
                                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                       at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                       at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                       at org.kb10uy.bhavaagra.MediaSelectorActivity.resolveMedia(MediaSelectorActivity.java:125)
                                                                       at org.kb10uy.bhavaagra.MediaSelectorActivity.onStart(MediaSelectorActivity.java:120)
                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                       at android.app.Activity.performStart(Activity.java:6253)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by hinaloe** [comment]
とりあえず修正できたんでPR送る
